# Generated by Django 4.0.3 on 2022-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cliques', models.IntegerField()),
                ('text', models.TextField()),
                ('image_one', models.ImageField(upload_to='graph')),
                ('image_two', models.ImageField(upload_to='graph')),
                ('text_one', models.TextField()),
                ('text_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_paulis', models.IntegerField()),
                ('physical_qubits', models.IntegerField()),
                ('error_plot', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
